In [21]:
import numpy as np
import statsmodels.api as sm
from sklearn.decomposition import PCA
from concurrent.futures import ProcessPoolExecutor, as_completed
import itertools
import logging
from one.api import ONE
from brainbox.io.one import SessionLoader
from brainwidemap import bwm_query, load_good_units, load_trials_and_mask, bwm_units
from collections import defaultdict
import pandas as pd
from manifold.decoding.functions.utils import check_config_decoding
import numpy as np
import pickle as pkl
from manifold.decoding.functions import nulldistributions
from communication_subspace.ibl_communication.utils import load_widefield_epoch
from tqdm import tqdm
from iblatlas.atlas import AllenAtlas
from iblatlas.regions import BrainRegions
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, balanced_accuracy_score
import warnings
from manifold.utils import get_trial_masks
from scipy.stats import pointbiserialr
from manifold.widefield_ppi import beryl_mapping,aggregate_by_parent
from matplotlib import pyplot as plt

with open("../data/processed/significant_stims_choice.pkl",'rb') as f:
    significant_preloads = pkl.load(f)


config = check_config_decoding()

In [32]:
from manifold.plot_spatial_alignment import plot_alignment

In [33]:
from glob import glob

In [34]:
files = glob('../data/generated/wifi/spatial_alignment/*.pkl')

In [41]:
df = pd.read_csv('../data/generated/wifi/spatial_alignment/batch_spatial_alignment_stats.csv')

In [46]:
df.sort_values('mean_acc_stim_incorrect')

,mean_corr_correct,mean_corr_incorrect,t_stat_corr_delta,p_val_corr_delta,mean_acc_stim_incorrect,mean_acc_choice_incorrect,t_stat_acc_delta,p_val_acc_delta,n_sessions,stim,choice
35,0.177353,0.102087,2.850559,7.015091e-03,0.448655,0.358622,6.160604,3.428301e-07,39,MO,AUD
32,0.240111,0.129370,3.987585,2.842092e-04,0.449668,0.275977,13.333364,4.147989e-16,40,MO,VIS
26,0.227407,0.126145,4.001369,2.727384e-04,0.449668,0.327905,6.882806,3.105239e-08,40,MO,PTLp
25,0.233989,0.136689,4.046693,2.381105e-04,0.449668,0.246818,14.410804,3.299699e-17,40,MO,RSP
33,0.226781,0.090812,5.707475,1.876344e-06,0.460124,0.324712,7.319967,1.483364e-08,36,RSP,PTLp
22,0.237713,0.097646,5.345824,5.628432e-06,0.460124,0.246179,13.509436,1.897411e-15,36,RSP,RSP
2,0.177096,0.080879,4.905139,1.318116e-05,0.475166,0.361832,8.305467,1.475391e-10,45,SS,AUD
8,0.165887,0.089187,4.215053,1.221087e-04,0.475166,0.408478,4.112756,1.683247e-04,45,SS,TEa
37,0.161692,0.064330,5.705857,9.115134e-07,0.475427,0.377107,5.973076,3.696529e-07,45,SS,PL
0,0.232191,0.112857,6.675807,3.087539e-08,0.475688,0.325076,9.944687,6.185508e-13,46,SS,PTLp
3,0.219132,0.101307,6.825983,1.846864e-08,0.475688,0.244417,18.121928,2.647262e-22,46,SS,RSP
4,0.239064,0.097556,6.511785,5.414508e-08,0.475688,0.201711,18.944799,4.502039e-23,46,SS,SS
7,0.234506,0.124888,5.299872,3.368862e-06,0.475688,0.276533,15.082474,3.254785e-19,46,SS,VIS
14,0.236316,0.097286,6.668708,3.163489e-08,0.475688,0.213218,20.327675,2.615788e-24,46,SS,MO
16,0.230389,0.086453,7.360230,3.886353e-09,0.482933,0.365061,6.900422,1.793734e-08,44,VIS,AUD
19,0.240582,0.129355,5.742457,8.652812e-07,0.482933,0.414788,4.228028,1.207553e-04,44,VIS,TEa
13,0.287679,0.086372,9.926112,8.393988e-13,0.484746,0.244972,18.567710,1.930187e-22,45,VIS,RSP
30,0.294162,0.071318,9.695083,1.721070e-12,0.484746,0.199635,18.754034,1.305392e-22,45,VIS,SS
29,0.297253,0.083764,9.574099,2.513258e-12,0.484746,0.213181,20.292191,5.784665e-24,45,VIS,MO
15,0.303568,0.104575,9.987279,6.948521e-13,0.484746,0.330626,9.707479,1.655751e-12,45,VIS,PTLp
10,0.313346,0.136154,8.131969,2.609462e-10,0.484746,0.276594,15.765035,1.026805e-19,45,VIS,VIS
34,0.201150,0.089230,5.254170,4.647530e-06,0.485979,0.375529,6.836650,2.490123e-08,43,VIS,PL
9,0.174426,0.085374,4.311321,1.203745e-04,0.493313,0.335269,8.625642,2.760441e-10,37,TEa,PTLp
27,0.156791,0.050335,5.311819,5.777145e-06,0.493313,0.203594,17.253282,5.467563e-19,37,TEa,SS
20,0.156653,0.091484,2.434158,2.001590e-02,0.493313,0.401339,5.374798,4.760458e-06,37,TEa,TEa
12,0.142037,0.035076,5.362235,4.947916e-06,0.493313,0.358065,7.465773,8.117904e-09,37,TEa,AUD
17,0.177753,0.072749,5.661787,1.968240e-06,0.493313,0.279498,12.594011,9.357070e-15,37,TEa,VIS
23,0.167518,0.037903,6.163331,4.206895e-07,0.493313,0.248842,16.621960,1.808436e-18,37,TEa,RSP
38,0.131970,0.053673,3.776144,5.934377e-04,0.493329,0.381384,6.856258,5.860962e-08,36,TEa,PL
11,0.201061,0.061859,5.776959,1.380587e-06,0.494841,0.366840,7.130269,2.216599e-08,37,PTLp,AUD
18,0.189482,0.088460,4.177871,1.788175e-04,0.494841,0.408830,4.456391,7.803139e-05,37,PTLp,TEa
24,0.252798,0.057005,7.255635,1.297298e-08,0.495367,0.218855,19.257116,7.115271e-21,38,PTLp,MO
21,0.244805,0.046111,7.025581,2.620827e-08,0.495367,0.204189,18.417931,3.178569e-20,38,PTLp,SS
6,0.240163,0.068405,6.790223,5.404120e-08,0.495367,0.251929,16.556889,1.079441e-18,38,PTLp,RSP
5,0.255186,0.092346,6.218420,3.179517e-07,0.495367,0.283830,13.203334,1.426893e-15,38,PTLp,VIS
1,0.268238,0.089442,6.609131,9.454875e-08,0.495367,0.336755,9.197248,4.266879e-11,38,PTLp,PTLp
28,0.170582,0.068277,5.175405,8.781491e-06,0.495516,0.380263,7.143197,2.132039e-08,37,PTLp,PL
31,0.159328,0.017161,3.332296,3.320679e-03,0.500596,0.195599,15.163116,1.971048e-12,21,AUD,SS
36,0.158270,0.057789,2.928201,8.313178e-03,0.500596,0.372661,4.826359,1.025611e-04,21,AUD,AUD

In [47]:
with open(files[0], 'rb') as f:
    ss = pkl.load(f)

In [49]:
ssdf = pd.DataFrame(ss)

In [52]:
ssdf

,region,epoch,cv_accuracy,cv_balanced_accuracy,correct_trial_indices,correct_logits,correct_true_labels,incorrect_trial_indices,incorrect_logits,incorrect_true_labels
0,MOB,stim,0.572464,0.571970,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-0.8717124633827573, 2.943167058946075, 0.197...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-3.9266221958478433, 2.1062361098438385, 0.06...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
1,MO,stim,0.608696,0.605114,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[14.4903535108617, 2.7980466123830197, -17.582...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-3.124578008730907, -3.1877960923903306, -6.2...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
2,SS,stim,0.565217,0.564078,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-3.3158119876556187, -0.4084847032919336, 1.1...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-8.027830240139263, 3.401121824614416, -5.099...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
3,PL,stim,0.536232,0.531881,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[0.31288031873399447, 0.9848641301039728, -0.0...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-1.1842214147827033, 0.9324576656452059, 0.03...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
4,RSP,stim,0.568841,0.567235,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-1.2157530545863178, 0.47627755913211167, -0....","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-2.6824297168774653, -0.17551990897279982, -0...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
5,TEa,stim,0.634058,0.632891,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-0.35866993703141736, -0.40866544117286735, -...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-0.8704123544603373, -0.6634413573745201, -0....","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
6,AUD,stim,0.623188,0.619949,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[0.22792852603719063, -0.4941084838186096, -0....","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-0.9944573962498211, 0.13091497590647191, 0.1...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
7,VIS,stim,0.688406,0.687816,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-0.128095381470982, -1.2427588125330762, -1.6...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-2.972212205147403, 1.6325484859897106, -0.24...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
8,PTLp,stim,0.634058,0.632260,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-0.3699409901861888, -1.6374277368648458, -0....","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-0.4901068093112892, 1.5078800383029043, 1.29...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
9,MOB,choice,0.768116,0.768624,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[5.385005348329091, 3.551809804038507, -2.9457...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-3.1102791634264535, -4.23013976939268, 0.532...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
10,MO,choice,0.851449,0.850379,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[1.1382837331716134, 1.4394856705529948, -2.00...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[1.2030249441922105, -1.3750060443757164, -3.4...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
11,SS,choice,0.855072,0.855114,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-0.14634635922575157, 7.445942317090134, -4.6...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[3.9412885375637807, -11.282370386489672, -5.9...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
12,PL,choice,0.630435,0.629735,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[-0.17305318292749083, 0.7862065717340093, -0....","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[0.23383902680759042, 0.07091492802634311, 0.0...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
13,RSP,choice,0.786232,0.785985,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[7.678845935411228, -0.5102470066134134, 1.486...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[11.441901384347876, -2.2499245533604526, -3.6...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
14,TEa,choice,0.750000,0.749369,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[1.8903281478390686, 1.545677760355494, -3.543...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[-1.3150611840976472, 0.4780736422238516, 1.64...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
15,AUD,choice,0.778986,0.778409,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[4.314248697164483, 1.3217636280269618, 1.0263...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[2.872000656890129, 0.19663098693743422, -1.18...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
16,VIS,choice,0.833333,0.833649,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[4.429050874131705, -0.4806381613830494, -4.76...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[2.1600357575631413, 2.747883041117252, 2.1701...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."
17,PTLp,choice,0.782609,0.782513,"[1, 2, 3, 4, 5, 7, 9, 11, 15, 16, 17, 18, 25, ...","[1.1152906711195971, 0.8987618355969152, -0.72...","[1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1...","[0, 8, 20, 22, 23, 27, 31, 33, 34, 36, 37, 44,...","[6.744254209339708, -0.7743846604579109, -1.54...","[-1.0, 1.0, 1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1..."